# Lesson 5: Files & Data IO (Input & Output)

At some point in your aerospace journey with Python, you will need to leverage files to get data for your program. Examples of scenarios where file handling becomes crucial include reading sensor data from spacecraft instruments, parsing telemetry logs for analysis, accessing configuration files for simulation parameters.

## Opening & Modifying Files 📃
Python has in-built support for accessing and altering files. 

You can open a file using the `open` command:

In [ ]:
file = open("sample.txt", "w")

The `w` stands for `write` and lets us write to a file.
Instead, you can use `r` for read-only or `a` for appending.

The code snippet below demonstrates how you can write text to a file named `sample.txt`

In [1]:
file = open("sample.txt", "w")
file.write('BLAST')
file.write('OFF')
file.close()

## Writing Data using Loops 🔄
You can write long-form datasets into a file using loops.
The following saves the names, surface gravity, and surface temperature of various planets into a file named `planets.txt`:

In [4]:
planet_names = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
# Hard-coded array of surface gravity (in multiples of Earth's gravity)
surface_gravity = [0.38, 0.91, 1.0, 0.38, 2.34, 0.93, 0.92, 1.12]
# Hard-coded array of surface temperature (in Kelvin)
surface_temperature = [440, 737, 288, 210, 120, 80, 60, 50]

file = open("planets.txt", "w")

for i in range(len(planet_names)):
    file.write(planet_names[i] + " ")
    file.write("Surface Gravity (g): " + str(surface_gravity[i]) + " ")
    file.write("Surface Temperature (K): " + str(surface_temperature[i]) + " \n")

file.close()

### Exercise 1: Saving Orbital Details 🪐
You are a planetary scientist tasked with saving orbital details about planets into a file for later use

#### Objective: 
- Initialize a text file named `orbital_details`
- Iterate over all the planets and save their orbital details into the text file

In [8]:
planet_names = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]

# Orbital periods (in Earth years)
orbital_periods = [0.24, 0.62, 1.0, 1.88, 11.86, 29.46, 84.01, 164.8]

# Axial tilts (in degrees)
axial_tilts = [0.03, 177.36, 23.44, 25.19, 3.13, 26.73, 82.23, 28.32]

## Working with loadtxt
You can also load text from files using the `loadtxt` command.
Suppose we have a text file called `spacecraft` containing thee columns `mass, fuel, and force`.
You can single out each of the column values into an array with their own variable using the code below:

In [14]:
import numpy as np
data = np.loadtxt("spacecraft.txt")
data = np.transpose(data) # transpose switches the rows and columns
mass = data[0]
fuel = data[1]
force = data[2]
print(mass)

[ 5.  12.1  7.3]


## Working with Astronomical FITS Files 🌌
Astronomical FITS (Flexible Image Transport System) files are a standard file format widely used in astronomy for storing and sharing astronomical data, including images, spectra, and tables. FITS files are designed to be flexible and efficient, allowing for the storage of large dataset.

### FITS File Structure
FITS files are comprised of two main components: `header` and `data` stored within HDU (Header Data Unit).
The `header` stores metadata information, such as observation details and instrument settings, while the `data` part contains the actual data, often represented as arrays.

In [13]:
from astropy.io import fits

# Open FITS file
hdul = fits.open('example.fits')

# Access HDUs
data_hdu = hdul[0]  # Access the primary HDU  

# Access data and header
data = data_hdu.data    # Get data array
header = data_hdu.header  # Get header information

print(data, header)

# Close FITS file
hdul.close()

[[0.1252262  0.78856681 0.76340433 ... 0.68677906 0.83367139 0.29958632]
 [0.19601932 0.57361986 0.98043251 ... 0.16136321 0.3754491  0.35797337]
 [0.44962573 0.97541743 0.99777408 ... 0.2103913  0.15822016 0.31916497]
 ...
 [0.91618878 0.22216225 0.77503183 ... 0.04216499 0.30171987 0.72717102]
 [0.56541479 0.14676798 0.0135142  ... 0.60697871 0.26601878 0.56936343]
 [0.50022191 0.4166072  0.40940887 ... 0.56810509 0.82001118 0.74196087]] SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    2 / number of array dimensions                     NAXIS1  =                  100                                                  NAXIS2  =                  100                                                  EXTEND  =                    T                                                  OBJECT  = 'Fake Image'                                                      

Congratulations for finishing the first module! At this point, you have grasped the fundamentals of Python and are ready to embark on your first programming project! After you complete the project, we will dive into using common aerospace libraries and plotting / visualizing data.