# Lesson 1: NumPy

## Packages in Python 📚
A Python package is a collection of modules. They are created by other developers to help you perform common tasks more easily without having to write all the code from scratch.

## Core Packages for Aerospace 🚀
In aerospace and astronomy, many core packages are commonly used to perform various tasks, including numerical simulations, data analysis, visualization, and more. Here are some essential packages for each field:

`numpy`: NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

`scipy`: SciPy is built on top of NumPy and provides additional functionality for scientific and technical computing. It includes modules for optimization, integration, interpolation, signal processing, linear algebra, and more.

`matplotlib`:Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It provides a MATLAB-like interface for generating plots and graphs, making it suitable for visualizing aerospace data. 

`pandas`: Pandas is a powerful data analysis and manipulation library that provides data structures and functions for working with structured data.

`astropy`: Astropy is a core package for astronomy in Python, providing a wide range of tools and utilities for astronomical data analysis and modeling.

## Getting Started with NumPy 🐍
NumPy is a fundamental package for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. In aerospace applications, NumPy is widely used for numerical simulations, data analysis, signal processing, and more. Learn more at: [https://numpy.org/](https://numpy.org/).

In [5]:
import numpy as np

## Arrays 🗂️
NumPy arrays and ndarrays (n-dimensional arrays) are the core data structure used for numerical computations. You can create arrays using  `np.array()` 

In NumPy dimensions are called **axes**. The number of axes is referred to as **rank**. 

In [7]:
# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


There are additional methods for creating specific arrays within NumPy. They include:

`np.zeros()` create an array filled with 0 of a specified shape

`np.ones()`  create an array filled with 1 of a specified shape

`np.arange()` create an array with evenly spaced values within a specified range

`np.linspace()` create an array with evenly spaced values over a specified interval

`np.full()` create a new NumPy array filled with a specified value

In [11]:
# Create a 1D array filled with zeros
zeros_1d = np.zeros(5)
print("1D Array filled with zeros:", zeros_1d)

# Create a 2D array filled with zeros
zeros_2d = np.zeros((3, 3))
print("2D Array filled with zeros:")
print(zeros_2d)

1D Array filled with zeros: [0. 0. 0. 0. 0.]
2D Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Create a 1D array filled with ones
ones_1d = np.ones(5)
print("1D Array filled with ones:", ones_1d)

# Create a 2D array filled with ones
ones_2d = np.ones((3, 3))
print("2D Array filled with ones:")
print(ones_2d)

1D Array filled with ones: [1. 1. 1. 1. 1.]
2D Array filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Create an array with values from 0 to 9
arr_range_1 = np.arange(10)
print("Array with values from 0 to 9:", arr_range_1)

# Create an array with values from 5 to 14
arr_range_2 = np.arange(5, 15)
print("Array with values from 5 to 14:", arr_range_2)

# Create an array with values from 0 to 9 with a step of 2
arr_range_3 = np.arange(0, 10, 2)
print("Array with values from 0 to 9 with a step of 2:", arr_range_3)

Array with values from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
Array with values from 5 to 14: [ 5  6  7  8  9 10 11 12 13 14]
Array with values from 0 to 9 with a step of 2: [0 2 4 6 8]


In [14]:
# Create an array with 10 evenly spaced values between 0 and 1
arr_linspace_1 = np.linspace(0, 1, 10)
print("Array with 10 evenly spaced values between 0 and 1:", arr_linspace_1)

# Create an array with 5 evenly spaced values between 1 and 10
arr_linspace_2 = np.linspace(1, 10, 5)
print("Array with 5 evenly spaced values between 1 and 10:", arr_linspace_2)

Array with 10 evenly spaced values between 0 and 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Array with 5 evenly spaced values between 1 and 10: [ 1.    3.25  5.5   7.75 10.  ]


In [17]:
# Create a 2x3 array filled with 5
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


Additional features you should know are `np.shape()` and `dtype`

`np.shape()` method returns a tuple indicating the dimensions of the array. For a 1D array, it returns a single-element tuple with the length of the array. For multidimensional arrays, it returns a tuple specifying the size of each dimension.

`dtype`  create an array filled with 1 of a specified shape

In [16]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("Shape of 1D array:", arr_1d.shape)  # Output: (5,)

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of 2D array:", arr_2d.shape)  # Output: (2, 3)

Shape of 1D array: (5,)
Shape of 2D array: (2, 3)


In [15]:
arr_int = np.array([1, 2, 3, 4, 5])
print("Data type of array with integers:", arr_int.dtype)  # Output: int64

# Create an array with floating-point elements
arr_float = np.array([1.0, 2.5, 3.7])
print("Data type of array with floats:", arr_float.dtype)  # Output: float64

Data type of array with integers: int64
Data type of array with floats: float64


## Array Operations ➗
NumPy supplies an assortment of methods to use for computing numerical operations on arrays. Array operations include:

### Element-wise Arithmetic Operations

In [21]:
# Create two NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Addition
result_add = np.add(arr1, arr2)
print("Element-wise addition:", result_add)

# Subtraction
result_sub = np.subtract(arr1, arr2)
print("Element-wise subtraction:", result_sub)

# Multiplication
result_mul = np.multiply(arr1, arr2)
print("Element-wise multiplication:", result_mul)

# Division
result_div = np.divide(arr2, arr1)
print("Element-wise division:", result_div)

Element-wise addition: [ 7  9 11 13 15]
Element-wise subtraction: [-5 -5 -5 -5 -5]
Element-wise multiplication: [ 6 14 24 36 50]
Element-wise division: [6.         3.5        2.66666667 2.25       2.        ]


### Scalar Arithmetic Operations

In [20]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Scalar addition
scalar_add = arr + 10
print("Scalar addition:", scalar_add)

# Scalar subtraction
scalar_sub = arr - 3
print("Scalar subtraction:", scalar_sub)

# Scalar multiplication
scalar_mul = arr * 2
print("Scalar multiplication:", scalar_mul)

# Scalar division
scalar_div = arr / 2
print("Scalar division:", scalar_div)

Scalar addition: [11 12 13 14 15]
Scalar subtraction: [-2 -1  0  1  2]
Scalar multiplication: [ 2  4  6  8 10]
Scalar division: [0.5 1.  1.5 2.  2.5]


### Element-wise Mathematical Functions

In [22]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Square root of each element
result_sqrt = np.sqrt(arr)
print("Square root of each element:", result_sqrt)

# Exponential of each element
result_exp = np.exp(arr)
print("Exponential of each element:", result_exp)

# Trigonometric functions
result_sin = np.sin(arr)
print("Sine of each element:", result_sin)

result_cos = np.cos(arr)
print("Cosine of each element:", result_cos)

result_tan = np.tan(arr)
print("Tangent of each element:", result_tan)

Square root of each element: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of each element: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine of each element: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine of each element: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangent of each element: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


### Exercise 1: Spacecraft Telemetry Modeling with NumPy Arrays 🚀 
You are part of a team developing a flight trajectory planning software for a space mission to Mars. The software requires efficient handling of numerical data for trajectory calculations and simulations.

#### Objectives:
- Generate a NumPy array representing time in seconds from t=0 to t=100 seconds with a step size of 1 second.
- Generate a NumPy array representing altitude in meters during the launch phase. The altitude should start at 0 meters and increase linearly with time at a constant rate of 100 meters per second.
- Calculate the velocity array using the altitude array. Assume constant acceleration due to gravity (9.81 m/s^2) during the launch phase.
- Calculate the acceleration array using a constant acceleration value of 9.81 m/s^2.
- Print the shape and data type of each generated NumPy array

In [23]:
gravity_acceleration = 9.81  # Constant acceleration due to gravity in m/s^2

## Random Number Generation 🦄
NumPy provides functions for generating random numbers and random arrays, including `np.random.rand()`, `np.random.randn()`, `np.random.randint()`, and more. 

`np.random.rand()` generates random numbers from a uniform distribution between 0 and 1

In [24]:
# Generate a 1D array of random numbers between 0 and 1
rand_array_1d = np.random.rand(5)
print("1D Array of random numbers between 0 and 1:")
print(rand_array_1d)

# Generate a 2D array of random numbers between 0 and 1
rand_array_2d = np.random.rand(2, 3)
print("\n2D Array of random numbers between 0 and 1:")
print(rand_array_2d)

1D Array of random numbers between 0 and 1:
[0.74452333 0.06345792 0.16023151 0.78127545 0.35980403]

2D Array of random numbers between 0 and 1:
[[0.81258543 0.04161309 0.41193043]
 [0.21494729 0.81923313 0.48843957]]


`np.random.randn()` generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [26]:
# Generate a 1D array of random numbers from a standard normal distribution
randn_array_1d = np.random.randn(5)
print("1D Array of random numbers from a standard normal distribution:")
print(randn_array_1d)

# Generate a 2D array of random numbers from a standard normal distribution
randn_array_2d = np.random.randn(2, 3)
print("\n2D Array of random numbers from a standard normal distribution:")
print(randn_array_2d)

1D Array of random numbers from a standard normal distribution:
[ 0.05487637 -0.82945917 -0.76285806 -0.64448938  3.12881364]

2D Array of random numbers from a standard normal distribution:
[[ 0.60633868 -1.9122101   0.06479419]
 [ 0.58945697  0.79181128  1.28282213]]


`np.random.randint()` generates random integers from a specified low (inclusive) to high (exclusive) range.

In [27]:
# Generate a 1D array of random integers between 0 and 9
randint_array_1d = np.random.randint(0, 10, size=5)
print("1D Array of random integers between 0 and 9:")
print(randint_array_1d)

# Generate a 2D array of random integers between 0 and 99
randint_array_2d = np.random.randint(0, 100, size=(2, 3))
print("\n2D Array of random integers between 0 and 99:")
print(randint_array_2d)

1D Array of random integers between 0 and 9:
[1 6 9 6 1]

2D Array of random integers between 0 and 99:
[[47 22 56]
 [91 46 80]]


## Array Comparison and Boolean Operations >
Array comparison and boolean operations in NumPy allow you to compare elements in arrays and perform logical operations efficiently. 

`np.where()` returns the indices of elements in an array that satisfy a given condition.

In [28]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Find indices where elements are greater than 2
indices = np.where(arr > 2)
print("Indices where elements are greater than 2:", indices)

Indices where elements are greater than 2: (array([2, 3, 4]),)


`ndarray.any()` returns True if ANY element in the array evaluates to True, otherwise False.

`ndarray.all()` returns True if ALL elements in the array evaluate to True, otherwise False.

In [29]:
# Create a NumPy array
arr = np.array([False, True, False, True])

# Test if any element is True
any_true = arr.any()
print("Any element is True:", any_true)

# Test if all elements are True
all_true = arr.all()
print("All elements are True:", all_true)

Any element is True: True
All elements are True: False


`np.logical_and()` performs element-wise logical AND operation between two arrays.
    
`np.logical_or()` performs element-wise logical OR operation between two arrays.
    
`np.logical_not()` performs element-wise logical NOT operation on an array.

In [30]:
# Create NumPy arrays
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

# Element-wise logical AND
result_and = np.logical_and(arr1, arr2)
print("Element-wise logical AND:", result_and)

# Element-wise logical OR
result_or = np.logical_or(arr1, arr2)
print("Element-wise logical OR:", result_or)

# Element-wise logical NOT
result_not = np.logical_not(arr1)
print("Element-wise logical NOT:", result_not)

Element-wise logical AND: [ True False False False]
Element-wise logical OR: [ True  True  True False]
Element-wise logical NOT: [False False  True  True]


## Array Manipulation 🏗️

### Indexing 
Array indexing in NumPy works similarly to Python lists, where you can access individual elements using square brackets `[]`

In [31]:
arr = np.array([1, 2, 3, 4, 5])
print("Element at index 0:", arr[0])  # Output: 1
print("Element at index 3:", arr[3])  # Output: 4
print("Element at index -1:", arr[-1])  # Output: 5

Element at index 0: 1
Element at index 3: 4
Element at index -1: 5


### Slicing 
Array slicing in NumPy allows you to extract subarrays (slices) from NumPy arrays using colon `:` notation

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("First three elements:", arr[:3])  # Output: [1 2 3]
print("Elements from index 3 to 6:", arr[3:7])  # Output: [4 5 6 7]
print("Even-indexed elements:", arr[::2])  # Output: [1 3 5 7 9]
print("Reverse the array:", arr[::-1])  # Output: [10  9  8  7  6  5  4  3  2  1]

First three elements: [1 2 3]
Elements from index 3 to 6: [4 5 6 7]
Even-indexed elements: [1 3 5 7 9]
Reverse the array: [10  9  8  7  6  5  4  3  2  1]


### Appending and Concatenating Arrays 

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Append arr2 to arr1
appended_arr = np.append(arr1, arr2)
print("Appended array:")
print(appended_arr)

# Concatenate arrays along axis 0 (along rows)
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated array along axis 0:")
print(concatenated_arr)

Appended array:
[1 2 3 4 5 6]
Concatenated array along axis 0:
[1 2 3 4 5 6]


### Flattening Arrays 

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print("Flattened array:")
print(flattened_arr)

Flattened array:
[1 2 3 4 5 6]


### Exercise 2: Mission Profiling 📡

#### Objectives:
- Use NumPy's random number generation functions to generate simulated altitude, velocity, and acceleration data.
- Assume that the flight data consists of 1000 data points each for altitude, velocity, and acceleration.
- Perform array indexing and slicing to extract subsets of data for analysis.
- Use array comparisons and conditional methods to identify critical points:
   - Critical altitude: Altitude above 5000 meters.
   - Critical velocity: Velocity greater than 300 meters per second.
   - Critical acceleration: Acceleration less than -9.8 meters per second squared (indicating deceleration).
- Concatenate arrays representing critical points to an array and print it out!

Well done! You have now covered the foundations of using NumPy!
Next up, we will cover the pandas library 🐼!